import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { env } from '../config.js';
import { logger } from '../logger.js';
import type { FortnightlyReport, Narrative, BuildIdea } from '@solis/shared';

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function stageEmoji(stage: string): string {
  switch (stage) {
    case 'EARLY': return '🔵';
    case 'EMERGING': return '🟡';
    case 'GROWING': return '🟠';
    case 'MAINSTREAM': return '🔴';
    default: return '⚪';
  }
}

function momentumArrow(momentum: string): string {
  switch (momentum) {
    case 'accelerating': return '↑';
    case 'stable': return '→';
    case 'decelerating': return '↓';
    default: return '→';
  }
}

function renderNarrative(n: Narrative, index: number): string {
  const lines = [
    `### ${index + 1}. ${stageEmoji(n.stage)} ${n.name}`,
    '',
    `**Stage:** ${n.stage} | **Momentum:** ${momentumArrow(n.momentum)} ${n.momentum} | **Confidence:** ${n.confidence}%`,
    '',
    n.description,
    '',
  ];

  if (n.signals.leading.length > 0) {
    lines.push('**Leading Signals (GitHub):**');
    for (const s of n.signals.leading) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  if (n.signals.coincident.length > 0) {
    lines.push('**Coincident Signals (Onchain/DeFi):**');
    for (const s of n.signals.coincident) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  if (n.signals.confirming.length > 0) {
    lines.push('**Confirming Signals (Market):**');
    for (const s of n.signals.confirming) {
      lines.push(`- ${s}`);
    }
    lines.push('');
  }

  if (n.relatedRepos.length > 0) {
    lines.push(`**Related repos:** ${n.relatedRepos.map(r => `\`${r}\``).join(', ')}`);
  }
  if (n.relatedTokens.length > 0) {
    lines.push(`**Related tokens:** ${n.relatedTokens.join(', ')}`);
  }
  if (n.relatedProtocols.length > 0) {
    lines.push(`**Related protocols:** ${n.relatedProtocols.join(', ')}`);
  }

  lines.push('');
  lines.push('---');
  lines.push('');

  return lines.join('\n');
}

function renderBuildIdea(idea: BuildIdea, index: number): string {
  return [
    `### ${index + 1}. ${idea.title}`,
    '',
    `**Difficulty:** ${idea.difficulty} | **Timeframe:** ${idea.timeframe}`,
    '',
    idea.description,
    '',
    `**Why now:** ${idea.whyNow}`,
    '',
    `**Tech stack:** ${idea.techStack.join(', ')}`,
    '',
    idea.existingProjects.length > 0
      ? `**Reference projects:** ${idea.existingProjects.join(', ')}`
      : '',
    '',
  ].filter(Boolean).join('\n');
}

export async function writeMarkdownReport(report: FortnightlyReport, date: string): Promise<string> {
  const dir = env.REPORTS_DIR;
  await mkdir(dir, { recursive: true });

  const path = join(dir, `${date}.md`);

  const lines = [
    `# SOLIS Report — ${formatDate(report.period.start)} to ${formatDate(report.period.end)}`,
    '',
    `*Generated: ${formatDate(report.generatedAt)}*`,
    '',
    '## Summary',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Repos analyzed | ${report.meta.totalReposAnalyzed} |`,
    `| Protocols analyzed | ${report.meta.totalProtocolsAnalyzed} |`,
    `| Tokens analyzed | ${report.meta.totalTokensAnalyzed} |`,
    `| Anomalies detected | ${report.meta.anomaliesDetected} |`,
    `| Narratives identified | ${report.meta.narrativesIdentified} |`,
    `| Build ideas generated | ${report.meta.buildIdeasGenerated} |`,
    `| LLM cost | $${report.meta.llmCostUsd.toFixed(4)} |`,
    `| Pipeline duration | ${(report.meta.pipelineDurationMs / 1000).toFixed(1)}s |`,
    '',
    '## Signal Stage Legend',
    '',
    '| Stage | Meaning |',
    '|-------|---------|',
    '| 🔵 EARLY | Only dev signals fire — highest alpha, market hasn\'t noticed |',
    '| 🟡 EMERGING | Devs + capital moving — narrative gaining traction |',
    '| 🟠 GROWING | All 3 layers align — mainstream adoption building |',
    '| 🔴 MAINSTREAM | Fully confirmed — likely already priced in |',
    '',
    '---',
    '',
    '## Narratives',
    '',
    ...report.narratives.map((n, i) => renderNarrative(n, i)),
    '## Build Ideas',
    '',
    ...report.buildIdeas.map((idea, i) => renderBuildIdea(idea, i)),
    '---',
    '',
    `## Data Sources`,
    '',
    '| Source | Layer | Data Points |',
    '|--------|-------|------------|',
    ...report.sources.map(s => `| ${s.name} | ${s.layer} | ${s.dataPoints} |`),
    '',
    '---',
    '',
    '*Report generated by [SOLIS](https://github.com/RECTOR-LABS/solis) — Open-source Solana narrative intelligence*',
    '',
  ];

  await writeFile(path, lines.join('\n'), 'utf-8');
  logger.info({ path, narratives: report.narratives.length, ideas: report.buildIdeas.length }, 'Markdown report written');

  return path;
}
